[build]
  base = "."
  publish = "public/"
  command = "make deploy-netlify"

# Redirect the default subdomain to the primary domain
[[redirects]]
  from = "https://200ok.netlify.app/*"
  to = "https://200ok.us/:splat"
  status = 301
  force = true
